import { SuportedLanguagesSource } from "./suported-languages-source.enum";

export const AVAILABLE_LANGUAGES_SOURCE = [
  { label: 'Árabe', value: SuportedLanguagesSource.AR },
  { label: 'Búlgaro', value: SuportedLanguagesSource.BG },
  { label: 'Tcheco', value: SuportedLanguagesSource.CS },
  { label: 'Dinamarquês', value: SuportedLanguagesSource.DA },
  { label: 'Alemão', value: SuportedLanguagesSource.DE },
  { label: 'Grego', value: SuportedLanguagesSource.EL },
  { label: 'Inglês', value: SuportedLanguagesSource.EN },
  { label: 'Espanhol', value: SuportedLanguagesSource.ES },
  { label: 'Estoniano', value: SuportedLanguagesSource.ET },
  { label: 'Finlandês', value: SuportedLanguagesSource.FI },
  { label: 'Francês', value: SuportedLanguagesSource.FR },
  { label: 'Húngaro', value: SuportedLanguagesSource.HU },
  { label: 'Indonésio', value: SuportedLanguagesSource.ID },
  { label: 'Italiano', value: SuportedLanguagesSource.IT },
  { label: 'Japonês', value: SuportedLanguagesSource.JA },
  { label: 'Coreano', value: SuportedLanguagesSource.KO },
  { label: 'Lituano', value: SuportedLanguagesSource.LT },
  { label: 'Letão', value: SuportedLanguagesSource.LV },
  { label: 'Norueguês', value: SuportedLanguagesSource.NB },
  { label: 'Holandês', value: SuportedLanguagesSource.NL },
  { label: 'Polonês', value: SuportedLanguagesSource.PL },
  { label: 'Português', value: SuportedLanguagesSource.PT },
  { label: 'Romeno', value: SuportedLanguagesSource.RO },
  { label: 'Russo', value: SuportedLanguagesSource.RU },
  { label: 'Eslovaco', value: SuportedLanguagesSource.SK },
  { label: 'Esloveno', value: SuportedLanguagesSource.SL },
  { label: 'Sueco', value: SuportedLanguagesSource.SV },
  { label: 'Turco', value: SuportedLanguagesSource.TR },
  { label: 'Ucraniano', value: SuportedLanguagesSource.UK },
  { label: 'Chinês', value: SuportedLanguagesSource.ZH },
];
