import { SuportedLanguagesTarget } from "./suported-languages-target.enum";

export const AVAILABLE_LANGUAGES_TARGET = [
  { label: 'Árabe', value: SuportedLanguagesTarget.AR },
  { label: 'Búlgaro', value: SuportedLanguagesTarget.BG },
  { label: 'Tcheco', value: SuportedLanguagesTarget.CS },
  { label: 'Dinamarquês', value: SuportedLanguagesTarget.DA },
  { label: 'Alemão', value: SuportedLanguagesTarget.DE },
  { label: 'Grego', value: SuportedLanguagesTarget.EL },
  { label: 'Inglês', value: SuportedLanguagesTarget.EN },
  { label: 'Inglês (EUA)', value: SuportedLanguagesTarget.EN_US },
  { label: 'Inglês (Reino Unido)', value: SuportedLanguagesTarget.EN_GB },
  { label: 'Espanhol', value: SuportedLanguagesTarget.ES },
  { label: 'Estoniano', value: SuportedLanguagesTarget.ET },
  { label: 'Finlandês', value: SuportedLanguagesTarget.FI },
  { label: 'Francês', value: SuportedLanguagesTarget.FR },
  { label: 'Húngaro', value: SuportedLanguagesTarget.HU },
  { label: 'Indonésio', value: SuportedLanguagesTarget.ID },
  { label: 'Italiano', value: SuportedLanguagesTarget.IT },
  { label: 'Japonês', value: SuportedLanguagesTarget.JA },
  { label: 'Coreano', value: SuportedLanguagesTarget.KO },
  { label: 'Lituano', value: SuportedLanguagesTarget.LT },
  { label: 'Letão', value: SuportedLanguagesTarget.LV },
  { label: 'Norueguês', value: SuportedLanguagesTarget.NB },
  { label: 'Holandês', value: SuportedLanguagesTarget.NL },
  { label: 'Polonês', value: SuportedLanguagesTarget.PL },
  { label: 'Português (Brasil)', value: SuportedLanguagesTarget.PT_BR },
  { label: 'Português (Portugal)', value: SuportedLanguagesTarget.PT_PT },
  { label: 'Romeno', value: SuportedLanguagesTarget.RO },
  { label: 'Russo', value: SuportedLanguagesTarget.RU },
  { label: 'Eslovaco', value: SuportedLanguagesTarget.SK },
  { label: 'Esloveno', value: SuportedLanguagesTarget.SL },
  { label: 'Sueco', value: SuportedLanguagesTarget.SV },
  { label: 'Turco', value: SuportedLanguagesTarget.TR },
  { label: 'Ucraniano', value: SuportedLanguagesTarget.UK },
  { label: 'Chinês', value: SuportedLanguagesTarget.ZH },
  { label: 'Chinês (Simplificado)', value: SuportedLanguagesTarget.ZHHANS },
  { label: 'Chinês (Tradicional)', value: SuportedLanguagesTarget.ZHHANT },
];
